#!name=Alight Motion

[Script]
Alightmotion = type=http-response,script-path=https://raw.githubusercontent.com/lonely0712/Scripts/refs/heads/main/script-json/Alightmotion.js,pattern=https://us-central1-alight-creative.cloudfunctions.net/getAccountStatusAndLicenses,max-size=131072,requires-body=1,timeout=10,script-update-interval=0,enable=true

[MITM]
hostname = %APPEND% us-central1-alight-creative.cloudfunctions.net